name: add-module-to-project
description: Add a new test module to the project
display-name: add-module-to-project
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
  - "Api"
types:
  - app
inputs:
  - label: Module name
    type: text
    name: module_name
    default: new-module


global-computed-inputs:
  module_name_kebabcase: "{{module_name|kebabcase}}"

hooks:
  - type: edit
    trigger: before-render
    path: settings.gradle.kts
    changes:
     - insert:
        line: -1
        value: "\ninclude(\"{{module_name_kebabcase}}\")"
        when:
            not-exists: "include(\"{{module_name_kebabcase}}\")"